/// Flutter icons VehispaceIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VehispaceIcon
///      fonts:
///       - asset: fonts/VehispaceIcon.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
///
import 'package:flutter/widgets.dart';

class VehispaceIcon {
  VehispaceIcon._();

  static const _kFontFam = 'VehispaceIcon';

  static const IconData towing = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData car1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData profile_1 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData tow_truck__2__1 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData list_1 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData vector__4_ = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData shop_1 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData supermarket_1 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData group_6 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData wheel_1 = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData vector__3_ = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData car_1 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData vector__2_ = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData vector__1_ = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData car__1__1 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData vector = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData settings_1 = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData signal = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData signal_1 = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData chart_bar = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData search_1 = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData group_4 = const IconData(0xe823, fontFamily: _kFontFam);
}
